package airportGUI;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.LinkedList;
import java.util.NoSuchElementException;
import java.util.Queue;
import java.util.Scanner;
import java.util.StringTokenizer;
import javax.swing.Timer;

/**
 *
 * @author Lhavanjan Suresh
 */
public class airportGUI extends javax.swing.JFrame {

    public static Queue<Integer> landing = new LinkedList<Integer>();
    public static Queue<Integer> takeOff = new LinkedList<Integer>();
    int interval = 4, loop = 0;
    Timer t;

    /**
     * Creates new form FileIOGUI
     */
    public airportGUI() {
        initComponents();
        File takeoffFile = new File("takeoffs.txt");
        File arrivalFile = new File("arrivals.txt");

        try {
            takeOff = readFile(takeoffFile, takeOff);
            landing = readFile(arrivalFile, landing);
            updateText(takeOff, 't');
            updateText(landing, 'a');
        } catch (FileNotFoundException ex) {
            System.out.println("File not found.");
        }
        t = new Timer(1000, new airportGUI.TimerListener());

    }

    private class TimerListener implements ActionListener {

        @Override
        public void actionPerformed(ActionEvent e) {

            if (loop < 2) {
                if (!landing.isEmpty()) {
                    statusLabel.setText("Flight " + landing.toString().substring(1, 5) + " is landing. " + interval);
                    interval--;
                }
                else{
                    loop = 3;
                    interval = 2;
                }

                if (interval == 0) {
                    landing.remove();
                    updateText(landing, 'a');
                    interval = 4;
                    loop++;
                }
                if (loop == 2) {
                    loop = 3;
                    interval = 2;
                }
            } else {
                if (!takeOff.isEmpty()) {
                    statusLabel.setText("Flight " + takeOff.toString().substring(1, 5) + " is taking off. " + interval);
                    interval--;
                }
                else{
                    loop = 0;
                    interval = 4;
                }
                if (interval == 0) {
                    takeOff.remove();
                    updateText(takeOff, 't');
                    interval = 2;
                    loop++;
                }
                if (loop == 4) {
                    loop = 0;
                    interval = 4;
                }
            }
            
            if (takeOff.isEmpty() && landing.isEmpty()){
                statusLabel.setText("Waiting for further flights.");
            }
            
        }
    }

    public void updateText(Queue<Integer> flightNum, char x) {
        String temp;
        StringTokenizer st;
        int tokens;
        if (x == 't') {
            temp = takeOff.toString().substring(1, takeOff.toString().length() - 1);
            st = new StringTokenizer(temp, ", ");
            temp = "";
            tokens = st.countTokens();
            for (int a = 0; tokens > a; a++) {
                temp = temp + st.nextToken() + "\n";
            }
            takeoffsTextArea.setText(temp);
        } else if (x == 'a') {
            temp = landing.toString().substring(1, landing.toString().length() - 1);
            st = new StringTokenizer(temp, ", ");
            temp = "";
            tokens = st.countTokens();
            for (int a = 0; tokens > a; a++) {
                temp = temp + st.nextToken() + "\n";
            }
            arrivalsTextArea.setText(temp);
        }
    }

    public static Queue<Integer> readFile(File file, Queue<Integer> action) throws FileNotFoundException {
        Scanner input = new Scanner(file); //creates file object
        try {
            //while input has next line
            while (true) {
                int values = Integer.parseInt(input.nextLine()); //Saves the line into an int
                action.add(values);
            }
        } catch (NoSuchElementException ex) {
        }
        input.close(); //releases the file for other use
        return action;
    }

    public static boolean checkVerification(String value) {
      
        try{
            Integer.parseInt(value);
        }catch (NumberFormatException ex) {
            return false;
        }
            return true;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        statusLabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        takeoffsTextArea = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        arrivalsTextArea = new javax.swing.JTextArea();
        startButton = new javax.swing.JButton();
        arrivingTextField = new javax.swing.JTextField();
        takeoffTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel10.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel10.setText("Airport Simulator (SUR)");

        statusLabel.setText("Press 'START' to begin simulation.");

        jLabel12.setText("Arrivals");

        jLabel13.setText("Takeoffs");

        takeoffsTextArea.setEditable(false);
        takeoffsTextArea.setColumns(20);
        takeoffsTextArea.setRows(5);
        takeoffsTextArea.setAutoscrolls(false);
        takeoffsTextArea.setFocusable(false);
        takeoffsTextArea.setRequestFocusEnabled(false);
        takeoffsTextArea.setVerifyInputWhenFocusTarget(false);
        jScrollPane1.setViewportView(takeoffsTextArea);

        arrivalsTextArea.setEditable(false);
        arrivalsTextArea.setColumns(20);
        arrivalsTextArea.setRows(5);
        arrivalsTextArea.setAutoscrolls(false);
        arrivalsTextArea.setFocusable(false);
        arrivalsTextArea.setRequestFocusEnabled(false);
        arrivalsTextArea.setVerifyInputWhenFocusTarget(false);
        jScrollPane2.setViewportView(arrivalsTextArea);

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        arrivingTextField.setText("jTextField2");
        arrivingTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrivingTextFieldActionPerformed(evt);
            }
        });

        takeoffTextField.setText("jTextField2");
        takeoffTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeoffTextFieldActionPerformed(evt);
            }
        });

        jLabel1.setText("Arriving Flight:");

        jLabel2.setText("Takeoff Flight:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(84, 84, 84))
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(statusLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(arrivingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(takeoffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(startButton)
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(statusLabel)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(startButton)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrivingTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(takeoffTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void arrivingTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrivingTextFieldActionPerformed
        // TODO add your handling code here:
        if (checkVerification(arrivingTextField.getText()) == true) {
            landing.add(Integer.parseInt(arrivingTextField.getText()));
            arrivingTextField.setText("");
            arrivalsTextArea.setText("");
            updateText(landing, 'a');
        } else {
            //ERROR MESSAGE
            System.out.println("Not valid int.");
        }

    }//GEN-LAST:event_arrivingTextFieldActionPerformed

    private void takeoffTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeoffTextFieldActionPerformed
        // TODO add your handling code here:
        if (checkVerification(takeoffTextField.getText()) == true) {
            takeOff.add(Integer.parseInt(takeoffTextField.getText()));
            takeoffTextField.setText("");
            takeoffsTextArea.setText("");
            updateText(takeOff, 't');
        } else {
            //ERROR MESSAGE
            System.out.println("Not valid int.");
        }
    }//GEN-LAST:event_takeoffTextFieldActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        // TODO add your handling code here:
        //landing 4, takeoff 2

        t.start();
    }//GEN-LAST:event_startButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(airportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(airportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(airportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(airportGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new airportGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea arrivalsTextArea;
    private javax.swing.JTextField arrivingTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton startButton;
    private javax.swing.JLabel statusLabel;
    private javax.swing.JTextField takeoffTextField;
    private javax.swing.JTextArea takeoffsTextArea;
    // End of variables declaration//GEN-END:variables
}
